name = "mist"
version = "0.14.2"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }
target = "erlang"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_erlang = "~> 0.23"
gleam_http = "~> 3.5"
gleam_otp = "~> 0.8"
glisten = "~> 0.9"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.0"
