name = "mist"
version = "4.0.7"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }
target = "erlang"
gleam = ">= 1.4.0"

[erlang]
application_start_module = "mist@internal@clock"

[dependencies]
gleam_erlang = "~> 0.24"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_otp = "~> 0.9"
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
hpack_erl = "~> 0.3"
logging = "~> 1.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gramps = ">= 3.0.0 and < 4.0.0"
glisten = ">= 7.0.0 and < 8.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.2"
