name = "mist"
version = "1.0.0"

licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "rawhat", repo = "mist" }
target = "erlang"
gleam = ">= 1.0.0"

[erlang]
application_start_module = "mist@internal@clock"

[dependencies]
birl = "~> 1.3"
gleam_erlang = "~> 0.24"
gleam_http = "~> 3.5"
gleam_otp = "~> 0.9"
gleam_stdlib = "~> 0.35 or ~> 1.0"
glisten = "~> 2.0"
gramps = { path = "../gramps" }
hpack_erl = "~> 0.3"
logging = "~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.2"
